config/routes.rb
Rails.application.routes.draw do

  
  get 'searches/search'
  resources :books, only: [:edit, :update, :index, :show, :create, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  get 'home/about'=>'homes#about'
  devise_for :users
  root to:"homes#top"
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationship, only:[:create, :destroy]
    member do
    get :follows, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   has_many :book_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   
   
   validates :title, presence: true
   validates :body, length: { minimum: 1, maximum: 200 }
   
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
  def get_image(width, height)
   unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_book.png')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
end 

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_user, only: [:edit, :update]
  def index
    @new_book = Book.new
    @books=Book.all
    @user=User.find(current_user.id)
    @following_users = @user.following_user
    @follower_users = @user.follower_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:notice] ="You have created book successfully."
    redirect_to book_path(@book.id)
   else
    @books=Book.all
    @user=User.find(current_user.id)
    @new_book = @book
    render :index
   end

  end

  def edit
    @book=Book.find(params[:id])
  end

  def show
    @new_book=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
    @book_comment = BookComment.new
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice: 'You have updated book successfully.'

    else
      render :edit
    end

  end


  private

  def book_params
    params.require(:book).permit(:title, :body,:image)
  end

  def is_matching_user
    unless Book.find(params[:id]).user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Editing Book</h1>
      <% render "template/error_mess", record: @book%>
        </ul>
        <% end %>
      <%= form_with model: @book do |f| %>
        <h4>Image</h4>
        <%= f.file_field :image, placeholder: "Book_image", accept: "image/*" %>
      
        <h4>Title</h4>
        <%= f.text_field :title ,class:"form-control input-lg"%>
        
        <h4>Opinion</h4>
        <%= f.text_area :body ,class:"form-control input-lg"%>
        <div>
        <%= f.submit 'Update Book' ,class:"btn btn-success m-1"%>
        </div>
        
      <% end %>
      
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
      
    </div>
    
  </div>
  
</div>

app/views/books/index.html.erb
<div class="container">
  
  <% if @new_book.errors.any? %>
  <%= @new_book.errors.count %>errors prohibited this obj from being saved:
  
  <ul>
    <% @new_book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
    <div class="search_form">
    <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
  <%= render 'template/list', user: @user ,new_book: @new_book %>
    <!-- ユーザーの投稿一覧 -->
    
    
  
  
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th>image</th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th>Favorite</th>
                        <th>Comment</th>
                        
                    </tr>
                </thead>
                <tbody>
                 <% @books.each do |book| %>
                    
                        <tr>
                            <td>
                              <div>
                                <%= link_to user_path(book.user.id) do %>
                                  <%= image_tag book.get_image(90,90) %>
                                <% end %>
                              </div>
                            </td>
                            
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                              <%= book.body %>
                            </td>
                            
                            <td id="favorite_btn_<%= book.id %>">
                             
                              <%= render 'favorites/favorite', book: book %>
                             
                            </td>
                            
                            <td>
                               <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div>
  <%= flash[:notice] %>
  </div>
  <%= render 'template/list', user: @user ,new_book: @new_book %>
    <!-- ユーザーの投稿一覧 -->

  

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
            <table class="table table-hover table-inverse">
                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                        <th>Favorite</th>
                        <th>Comment</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>

                        <tr>
                            <td>
                              <div>
                                <%= link_to book_path(@book.id) do %>
                                  <%= image_tag @book.get_image(90,90) %>
                                <% end %>
                              </div>
                              <%= link_to user_path(@user.id) do %>
                                <%=@user.name%>
                              <% end %>
                            </td>
                            <td>
                                <%= link_to book_path(@book.id) do %>
                                    <%= @book.title %>
                                <% end %>
                            </td>
                            <td>
                              <%= @book.body %>
                            </td>
                            <td id="favorite_btn_<%= @book.id %>">
                             
                              <%= render 'favorites/favorite', book: @book %>
                             
                            </td>
                            </td>
                            <td>
                              <p>コメント数：<%= @book.book_comments.count %></p>
                            </td>

                            <td>
                             <% if current_user==@book.user %>
                                <%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-success" %>
                                <%= link_to "Destroy",book_path(@book.id),class:"btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
                             <% end %>
                            </td>
                            <td>

                            </td>
                        </tr>

                </tbody>
            </table>

            
              
              
            <div id=comment_<%= @book.id %>>
              <%=render 'book_comments/comment', {book: @book, book_comment: @book_comment} %>
            </div>


    </div>
  </div>
</div>