config/routes.rb
Rails.application.routes.draw do

  
  get 'searches/search'
  resources :books, only: [:edit, :update, :index, :show, :create, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  get 'home/about'=>'homes#about'
  devise_for :users
  root to:"homes#top"
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationship, only:[:create, :destroy]
    member do
    get :follows, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range =params[:range]
    @word =params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
     <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td>
                              <%= image_tag user.get_profile_image(90,90) %>
                            </td>
                            <td>
                              <%= user.name %>
                            </td>
                            <td>
                              <% if current_user.following?(user)%>
                               <%= link_to 'フォロー外す', user_relationship_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
                              <% else %>
                               <%= link_to 'フォローする', user_relationship_path(user.id), method: :post, class: "btn-sm btn-success" %>
                              <% end %>
                              
                            </td>
                            <td><%=link_to "Show", user_path(user.id) %></td>
                        </tr>
                    <% end %>
                </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
                 <% @books.each do |book| %>
                    
                        <tr>
                            <td>
                              <div>
                                <%= link_to user_path(book.user.id) do %>
                                  <%= image_tag book.user.get_profile_image(90,90) %>
                                <% end %>
                              </div>
                            </td>
                            
                            <td>
                                <%= link_to book_path(book.id) do %>
                                    <%= book.title %>
                                <% end %>
                            </td>
                            <td>
                              <%= book.body %>
                            </td>
                            
                            <td>
                              <% if book.favorited_by?(current_user) %>
                               <p>
                                  <%= link_to book_favorites_path(book), method: :delete do %>
                                    <i class="fas fa-heart"></i><%= book.favorites.count %> いいね
                                  <% end %>
                                </p>
                                <% else %>
                                <p>
                                  <%= link_to book_favorites_path(book), method: :post do %>
                                    <i class="fas fa-heart"></i><%= book.favorites.count %> いいね
                                  <% end %>
                                </p>
                              <% end %>
                            </td>
                            
                            <td>
                               <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
  <% end %>
</table>