config/routes.rb
Rails.application.routes.draw do

  
  get 'searches/search'
  resources :books, only: [:edit, :update, :index, :show, :create, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end
  get 'home/about'=>'homes#about'
  devise_for :users
  root to:"homes#top"
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationship, only:[:create, :destroy]
    member do
    get :follows, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/59914bf2d7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="shadow-sm">

      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
          <a class="navbar-brand text-white" href="/">
            Bookers
          </a>
          <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home "></i>Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-users"></i>Users
                <% end %>

              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>Books
                <% end %>

              </li>
              <li class="nav-item">
                <%= link_to  destroy_user_session_path, class: 'nav-link text-light', method: :delete do%>
                <i class="fas fa-sign-out-alt"></i>logout
                <% end %>



              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home "></i>Home
                <% end %>
              </li>
              
              <li class="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>About
                <% end %>

              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>sign up
                <% end %>

              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>login
                <% end %>
              </li>




            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    
    <%= yield %>

    <footer class="footer text-center p-7 ">
      <div class="container">
        <p class="text-muted">CopyRight Infratop.inc</p>
      </div>
    </footer>

  </body>
</html>